import type { Product } from "./types";

function p(
  product: Omit<Product, "inStock" | "stockQty" | "unit" | "tags" | "attributes"> &
    Partial<Pick<Product, "inStock" | "stockQty" | "unit" | "tags" | "attributes" | "pack">>,
): Product {
  return {
    unit: "шт",
    inStock: true,
    stockQty: 48,
    tags: [],
    attributes: {},
    ...product,
  };
}

export const PRODUCTS: Product[] = [
  p({
    id: "148201",
    sku: "148201",
    name: "Принтер лазерный HP LaserJet 107a, A4, 20 стр/мин",
    brand: "HP",
    department: "print",
    category: "Принтеры лазерные",
    price: 11990,
    stockQty: 14,
    attributes: { format: "A4", color: "ч/б", type: "лазерный" },
    tags: ["оргтехника", "печать"],
    description: "Компактный монохромный лазерный принтер для небольшого офиса. USB-подключение.",
  }),
  p({
    id: "148202",
    sku: "W1107A",
    name: "Картридж оригинальный HP 107A (W1107A) чёрный, 1000 стр.",
    brand: "HP",
    department: "print",
    category: "Картриджи лазерные",
    price: 4590,
    attributes: { color: "чёрный", resource: "1000", oem: "107A" },
    tags: ["расходник", "оригинал"],
    description: "Оригинальный тонер-картридж HP 107A для LaserJet 107a / 107w.",
  }),
  p({
    id: "148203",
    sku: "K-107A",
    name: "Картридж совместимый Комус 107A чёрный, 1000 стр.",
    brand: "Комус",
    department: "print",
    category: "Картриджи лазерные",
    price: 1290,
    stockQty: 86,
    attributes: { color: "чёрный", resource: "1000", oem: "107A" },
    tags: ["расходник", "совместимый"],
    description: "Совместимый картридж 107A собственной торговой марки. Экономия при той же ёмкости.",
  }),
  p({
    id: "148210",
    sku: "C11CJ67405",
    name: "МФУ струйное Epson EcoTank L3250, цветное, Wi-Fi",
    brand: "Epson",
    department: "print",
    category: "МФУ струйные",
    price: 18990,
    stockQty: 9,
    attributes: { format: "A4", color: "цветной", type: "струйный" },
    tags: ["оргтехника", "печать", "сканер"],
    description: "Цветное МФУ с СНПЧ. Печать, сканирование, копирование. Низкая стоимость отпечатка.",
  }),
  p({
    id: "148211",
    sku: "C13T00S14A",
    name: "Чернила Epson 103 EcoTank чёрные, 65 мл",
    brand: "Epson",
    department: "print",
    category: "Чернила",
    price: 890,
    attributes: { color: "чёрный", volume: "65 мл" },
    tags: ["расходник", "оригинал"],
    description: "Оригинальные чернила Epson 103 Black для серии EcoTank L3250 / L3251 / L3210.",
  }),
  p({
    id: "148212",
    sku: "C13T00S24A",
    name: "Чернила Epson 103 EcoTank голубые, 65 мл",
    brand: "Epson",
    department: "print",
    category: "Чернила",
    price: 890,
    attributes: { color: "голубой", volume: "65 мл" },
    tags: ["расходник", "оригинал"],
    description: "Оригинальные чернила Epson 103 Cyan.",
  }),
  p({
    id: "148213",
    sku: "C13T00S34A",
    name: "Чернила Epson 103 EcoTank пурпурные, 65 мл",
    brand: "Epson",
    department: "print",
    category: "Чернила",
    price: 890,
    attributes: { color: "пурпурный", volume: "65 мл" },
    tags: ["расходник", "оригинал"],
    description: "Оригинальные чернила Epson 103 Magenta.",
  }),
  p({
    id: "148214",
    sku: "C13T00S44A",
    name: "Чернила Epson 103 EcoTank жёлтые, 65 мл",
    brand: "Epson",
    department: "print",
    category: "Чернила",
    price: 890,
    attributes: { color: "жёлтый", volume: "65 мл" },
    tags: ["расходник", "оригинал"],
    description: "Оригинальные чернила Epson 103 Yellow.",
  }),
  p({
    id: "148220",
    sku: "DCPL2520DWR1",
    name: "МФУ лазерное Brother DCP-L2520DWR, ч/б, дуплекс, Wi-Fi",
    brand: "Brother",
    department: "print",
    category: "МФУ лазерные",
    price: 21490,
    stockQty: 6,
    attributes: { format: "A4", color: "ч/б", type: "лазерный" },
    tags: ["оргтехника", "печать"],
    description: "Монохромное лазерное МФУ с автодуплексом. Для рабочих групп до 5 человек.",
  }),
  p({
    id: "148221",
    sku: "TN2375",
    name: "Тонер-картридж Brother TN-2375 чёрный, 2600 стр.",
    brand: "Brother",
    department: "print",
    category: "Картриджи лазерные",
    price: 3890,
    attributes: { color: "чёрный", resource: "2600", oem: "TN-2375" },
    tags: ["расходник", "оригинал"],
    description: "Оригинальный тонер Brother TN-2375 для DCP-L2520DWR и линейки HL-L2300.",
  }),
  p({
    id: "148222",
    sku: "DR2335",
    name: "Фотобарабан Brother DR-2335, 12000 стр.",
    brand: "Brother",
    department: "print",
    category: "Фотобарабаны",
    price: 5290,
    attributes: { resource: "12000", oem: "DR-2335" },
    tags: ["расходник", "оригинал"],
    description: "Оригинальный барабан Brother DR-2335. Меняется реже тонера.",
  }),
  p({
    id: "148301",
    sku: "5746701",
    name: "Ламинатор Fellowes Saturn 3i A4, 125 мкм",
    brand: "Fellowes",
    department: "print",
    category: "Ламинаторы",
    price: 7490,
    stockQty: 11,
    attributes: { format: "A4" },
    tags: ["оргтехника"],
    description: "Настольный ламинатор для документов, бейджей и меню. Готовность за 60 секунд.",
  }),
  p({
    id: "148302",
    sku: "LAMA4100",
    name: "Плёнка для ламинирования A4, 100 мкм, 100 шт.",
    brand: "Комус",
    department: "print",
    category: "Плёнка для ламинирования",
    price: 690,
    unit: "упак",
    pack: "100 шт.",
    attributes: { format: "A4", thickness: "100" },
    tags: ["расходник"],
    description: "Глянцевые пакеты для горячего ламинирования формата A4.",
  }),
  p({
    id: "148303",
    sku: "LAMA480",
    name: "Плёнка для ламинирования A4, 80 мкм, 100 шт.",
    brand: "Комус",
    department: "print",
    category: "Плёнка для ламинирования",
    price: 520,
    unit: "упак",
    pack: "100 шт.",
    attributes: { format: "A4", thickness: "80" },
    tags: ["расходник"],
    description: "Тонкая плёнка 80 мкм — для многостраничных документов и архива.",
  }),
  p({
    id: "148310",
    sku: "BR-A4",
    name: "Брошюратор на пластиковую пружину Brauberg A4",
    brand: "Brauberg",
    department: "print",
    category: "Брошюраторы",
    price: 5690,
    attributes: { format: "A4" },
    tags: ["оргтехника"],
    description: "Перфорация до 8 листов, переплёт до 120 листов. Для регламентов и презентаций.",
  }),
  p({
    id: "148311",
    sku: "SPR-8",
    name: "Пружины пластиковые 8 мм, 100 шт., чёрные",
    brand: "Комус",
    department: "print",
    category: "Пружины для брошюрования",
    price: 280,
    unit: "упак",
    pack: "100 шт.",
    attributes: { diameter: "8 мм", color: "чёрный" },
    tags: ["расходник"],
    description: "Пружины 8 мм — до 40 листов 80 г/м².",
  }),
  p({
    id: "148312",
    sku: "SPR-12",
    name: "Пружины пластиковые 12 мм, 100 шт., чёрные",
    brand: "Комус",
    department: "print",
    category: "Пружины для брошюрования",
    price: 340,
    unit: "упак",
    pack: "100 шт.",
    attributes: { diameter: "12 мм", color: "чёрный" },
    tags: ["расходник"],
    description: "Пружины 12 мм — до 80 листов.",
  }),
  p({
    id: "148313",
    sku: "COV-A4",
    name: "Обложки для брошюрования A4, картон, 100 шт.",
    brand: "Комус",
    department: "print",
    category: "Обложки для брошюрования",
    price: 410,
    unit: "упак",
    pack: "100 шт.",
    attributes: { format: "A4" },
    tags: ["расходник"],
    description: "Плотные обложки под пластиковую пружину. Цвет — слоновая кость.",
  }),
  p({
    id: "148320",
    sku: "FS-8C",
    name: "Уничтожитель документов Fellowes Powershred 8C",
    brand: "Fellowes",
    department: "print",
    category: "Уничтожители документов",
    price: 9990,
    stockQty: 7,
    attributes: { security: "P-4" },
    tags: ["оргтехника", "безопасность"],
    description: "Секретность P-4, 8 листов за проход, корзина 14 л. Для кабинета руководителя.",
  }),
  p({
    id: "148321",
    sku: "OIL-SH",
    name: "Масло для уничтожителей документов, 120 мл",
    brand: "Fellowes",
    department: "print",
    category: "Масло для шредеров",
    price: 490,
    attributes: { volume: "120 мл" },
    tags: ["расходник"],
    description: "Смазка режущего блока. Продлевает срок службы шредера.",
  }),

  p({
    id: "110101",
    sku: "SN-A4-80",
    name: "Бумага офисная Снегурочка A4, 80 г/м², 500 л.",
    brand: "Снегурочка",
    department: "paper",
    category: "Бумага офисная A4",
    price: 449,
    unit: "пачка",
    pack: "500 л.",
    stockQty: 240,
    attributes: { format: "A4", density: "80" },
    tags: ["расходник", "печать"],
    description: "Классическая офисная бумага для лазерной и струйной печати. Белизна 146% CIE.",
  }),
  p({
    id: "110102",
    sku: "KOM-DOC-A4",
    name: "Бумага офисная Комус Документ Business A4, 80 г/м², 500 л.",
    brand: "Комус",
    department: "paper",
    category: "Бумага офисная A4",
    price: 429,
    unit: "пачка",
    pack: "500 л.",
    stockQty: 310,
    attributes: { format: "A4", density: "80" },
    tags: ["расходник", "печать"],
    description: "Собственная марка Комус. Стабильная подача в принтерах и МФУ.",
  }),
  p({
    id: "110103",
    sku: "IQ-SEL-A4",
    name: "Бумага офисная IQ Selection A4, 80 г/м², 500 л.",
    brand: "IQ",
    department: "paper",
    category: "Бумага офисная A4",
    price: 589,
    unit: "пачка",
    pack: "500 л.",
    stockQty: 64,
    attributes: { format: "A4", density: "80" },
    tags: ["печать"],
    description: "Премиальная бумага для цветной печати и внешней корреспонденции.",
  }),
  p({
    id: "110110",
    sku: "SN-A3-80",
    name: "Бумага офисная Снегурочка A3, 80 г/м², 500 л.",
    brand: "Снегурочка",
    department: "paper",
    category: "Бумага офисная A3",
    price: 899,
    unit: "пачка",
    pack: "500 л.",
    attributes: { format: "A3", density: "80" },
    tags: ["расходник", "печать"],
    description: "Формат A3 для чертежей, разворотов и плакатов.",
  }),
  p({
    id: "110120",
    sku: "LOM-PHOTO",
    name: "Фотобумага Lomond A4, глянцевая, 230 г/м², 50 л.",
    brand: "Lomond",
    department: "paper",
    category: "Фотобумага",
    price: 540,
    unit: "упак",
    pack: "50 л.",
    attributes: { format: "A4", density: "230" },
    tags: ["печать"],
    description: "Для струйной фотопечати: презентации, таблички, объявления.",
  }),
  p({
    id: "110130",
    sku: "FLIP-PAPER",
    name: "Бумага для флипчарта 65×100 см, 20 л.",
    brand: "Комус",
    department: "paper",
    category: "Бумага для флипчарта",
    price: 390,
    unit: "блок",
    pack: "20 л.",
    attributes: { format: "65x100" },
    tags: ["расходник"],
    description: "Нелинованные листы на склейке. Подходит к стандартным флипчартам 70×100.",
  }),

  p({
    id: "120201",
    sku: "ST-10-EC",
    name: "Степлер Attache Economy №10, до 10 листов",
    brand: "Attache",
    department: "stationery",
    category: "Степлеры",
    price: 119,
    stockQty: 180,
    attributes: { size: "№10", capacity: "10" },
    tags: ["канцелярия"],
    description: "Лёгкий степлер для ежедневной сшивки. Корпус из пластика.",
  }),
  p({
    id: "120202",
    sku: "STAPLE-10",
    name: "Скобы для степлера №10, 1000 шт.",
    brand: "Attache",
    department: "stationery",
    category: "Скобы для степлера",
    price: 39,
    unit: "упак",
    pack: "1000 шт.",
    stockQty: 500,
    attributes: { size: "№10" },
    tags: ["расходник"],
    description: "Омеднённые скобы №10. Совместимы со степлерами малого размера.",
  }),
  p({
    id: "120203",
    sku: "STAPLE-246",
    name: "Скобы для степлера №24/6, 1000 шт.",
    brand: "Attache",
    department: "stationery",
    category: "Скобы для степлера",
    price: 45,
    unit: "упак",
    pack: "1000 шт.",
    stockQty: 420,
    attributes: { size: "№24/6" },
    tags: ["расходник"],
    description: "Стандартные скобы 24/6 для степлеров среднего размера.",
  }),
  p({
    id: "120210",
    sku: "ST-23-PWR",
    name: "Степлер мощный Brauberg «Heavy Duty», до 100 листов, №23",
    brand: "Brauberg",
    department: "stationery",
    category: "Степлеры",
    price: 1890,
    attributes: { size: "№23", capacity: "100" },
    tags: ["канцелярия"],
    description: "Металлический степлер для толстых подборок и архива.",
  }),
  p({
    id: "120211",
    sku: "STAPLE-2313",
    name: "Скобы для степлера №23/13, 1000 шт.",
    brand: "Brauberg",
    department: "stationery",
    category: "Скобы для степлера",
    price: 89,
    unit: "упак",
    pack: "1000 шт.",
    attributes: { size: "№23/13" },
    tags: ["расходник"],
    description: "Длинные скобы 23/13 для мощных степлеров — до 80–100 листов.",
  }),
  p({
    id: "120220",
    sku: "HP-20",
    name: "Дырокол Attache до 20 листов, с линейкой",
    brand: "Attache",
    department: "stationery",
    category: "Дыроколы",
    price: 249,
    attributes: { capacity: "20" },
    tags: ["канцелярия"],
    description: "Два отверстия под папку-регистратор. Металлический механизм.",
  }),
  p({
    id: "120230",
    sku: "REG-75",
    name: "Папка-регистратор Комус, 75 мм, А4, ПВХ, синяя",
    brand: "Комус",
    department: "stationery",
    category: "Папки-регистраторы",
    price: 189,
    stockQty: 96,
    attributes: { format: "A4", width: "75 мм", color: "синий" },
    tags: ["архив"],
    description: "Корешок 75 мм, металлическое кольцевое крепление. Для договоров и актов.",
  }),
  p({
    id: "120231",
    sku: "REG-50",
    name: "Папка-регистратор Комус, 50 мм, А4, ПВХ, красная",
    brand: "Комус",
    department: "stationery",
    category: "Папки-регистраторы",
    price: 159,
    attributes: { format: "A4", width: "50 мм", color: "красный" },
    tags: ["архив"],
    description: "Узкий корешок 50 мм — когда документы ещё не выросли в том.",
  }),
  p({
    id: "120232",
    sku: "FILE-A4-100",
    name: "Файлы-вкладыши А4, 30 мкм, 100 шт.",
    brand: "Комус",
    department: "stationery",
    category: "Файлы",
    price: 129,
    unit: "упак",
    pack: "100 шт.",
    stockQty: 210,
    attributes: { format: "A4" },
    tags: ["расходник", "архив"],
    description: "Прозрачные файлы с перфорацией. В папку-регистратор и скоросшиватель.",
  }),
  p({
    id: "120240",
    sku: "PILOT-BPS",
    name: "Ручка шариковая Pilot BPS-GP, 0,5 мм, синяя",
    brand: "Pilot",
    department: "stationery",
    category: "Ручки шариковые",
    price: 89,
    stockQty: 340,
    attributes: { color: "синий", tip: "0,5" },
    tags: ["канцелярия"],
    description: "Резиновый грип, надёжный стержень. Базовая ручка для офиса.",
  }),
  p({
    id: "120241",
    sku: "PILOT-RFJS",
    name: "Стержень шариковый Pilot RFJS-GP, 0,5 мм, синий",
    brand: "Pilot",
    department: "stationery",
    category: "Стержни для ручек",
    price: 45,
    attributes: { color: "синий", tip: "0,5" },
    tags: ["расходник"],
    description: "Сменный стержень для Pilot BPS-GP и Super Grip.",
  }),
  p({
    id: "120242",
    sku: "EK-R301",
    name: "Ручка шариковая ErichKrause R-301, 0,7 мм, синяя",
    brand: "ErichKrause",
    department: "stationery",
    category: "Ручки шариковые",
    price: 29,
    stockQty: 800,
    attributes: { color: "синий", tip: "0,7" },
    tags: ["канцелярия"],
    description: "Шестигранный корпус. Массовая закупка в отделы.",
  }),
  p({
    id: "120250",
    sku: "MRK-BOARD",
    name: "Маркер для белых досок Attache, чёрный",
    brand: "Attache",
    department: "stationery",
    category: "Маркеры для досок",
    price: 69,
    attributes: { color: "чёрный" },
    tags: ["расходник"],
    description: "Спиртовая основа, стирается губкой. Для магнитно-маркерных досок.",
  }),
  p({
    id: "120251",
    sku: "MRK-SET4",
    name: "Набор маркеров для досок Attache, 4 цвета",
    brand: "Attache",
    department: "stationery",
    category: "Маркеры для досок",
    price: 249,
    unit: "набор",
    pack: "4 шт.",
    attributes: { color: "набор" },
    tags: ["расходник"],
    description: "Чёрный, синий, красный, зелёный — стандарт переговорной.",
  }),
  p({
    id: "120252",
    sku: "SPONGE-WB",
    name: "Губка для магнитно-маркерной доски, с магнитом",
    brand: "Комус",
    department: "stationery",
    category: "Губки для досок",
    price: 119,
    tags: ["расходник"],
    description: "Держится на доске. Сменные войлочные накладки.",
  }),
  p({
    id: "120253",
    sku: "MAG-20",
    name: "Магниты для доски, 20 мм, 10 шт.",
    brand: "Комус",
    department: "stationery",
    category: "Магниты",
    price: 159,
    unit: "набор",
    pack: "10 шт.",
    tags: ["аксессуар"],
    description: "Неодимовые магниты. Удержат несколько листов A4.",
  }),
  p({
    id: "120260",
    sku: "BOARD-90120",
    name: "Доска магнитно-маркерная 90×120 см, алюминиевая рамка",
    brand: "Комус",
    department: "stationery",
    category: "Доски магнитно-маркерные",
    price: 4290,
    stockQty: 8,
    attributes: { size: "90x120" },
    tags: ["переговорные"],
    description: "Лак покрытие, скрытое крепление. Для кабинета и переговорной.",
  }),
  p({
    id: "120261",
    sku: "FLIP-TRIPOD",
    name: "Флипчарт на треноге, 70×100 см",
    brand: "Комус",
    department: "stationery",
    category: "Флипчарты",
    price: 3890,
    stockQty: 5,
    attributes: { size: "70x100" },
    tags: ["переговорные"],
    description: "Регулировка высоты, лоток для маркеров, колёсики.",
  }),
  p({
    id: "120270",
    sku: "GLUE-STICK",
    name: "Клей-карандаш ErichKrause, 21 г",
    brand: "ErichKrause",
    department: "stationery",
    category: "Клей",
    price: 59,
    tags: ["канцелярия"],
    description: "ПВА-основа, не морщит бумагу. Для аппликаций и конвертов.",
  }),
  p({
    id: "120271",
    sku: "GLUE-GUN",
    name: "Пистолет клеевой, 40 Вт, стержни 7 мм",
    brand: "Комус",
    department: "stationery",
    category: "Клеевые пистолеты",
    price: 490,
    attributes: { diameter: "7 мм" },
    tags: ["канцелярия"],
    description: "Для упаковки подарков, оформления витрин и мелкого ремонта.",
  }),
  p({
    id: "120272",
    sku: "GLUE-STICKS7",
    name: "Стержни клеевые 7 мм, 10 шт., прозрачные",
    brand: "Комус",
    department: "stationery",
    category: "Клеевые стержни",
    price: 89,
    unit: "упак",
    pack: "10 шт.",
    attributes: { diameter: "7 мм" },
    tags: ["расходник"],
    description: "Универсальный термоклей. Совместимы с пистолетами 7 мм.",
  }),
  p({
    id: "120280",
    sku: "TAPE-19",
    name: "Клейкая лента канцелярская 19 мм × 33 м, прозрачная",
    brand: "Комус",
    department: "stationery",
    category: "Скотч канцелярский",
    price: 42,
    attributes: { width: "19 мм" },
    tags: ["расходник"],
    description: "Для упаковки документов и мелкого ремонта бумаги.",
  }),
  p({
    id: "120281",
    sku: "TAPE-DISP",
    name: "Диспенсер настольный для канцелярской ленты 19 мм",
    brand: "Attache",
    department: "stationery",
    category: "Диспенсеры для скотча",
    price: 219,
    attributes: { width: "19 мм" },
    tags: ["аксессуар"],
    description: "Утяжелённое основание. Лента отматывается одной рукой.",
  }),
  p({
    id: "120290",
    sku: "SCISS-16",
    name: "Ножницы Attache 16 см, с пластиковыми ручками",
    brand: "Attache",
    department: "stationery",
    category: "Ножницы",
    price: 129,
    tags: ["канцелярия"],
    description: "Острые лезвия из нержавеющей стали. Для бумаги и плёнки.",
  }),
  p({
    id: "120300",
    sku: "SDC-444S",
    name: "Калькулятор настольный Citizen SDC-444S, 12 разрядов",
    brand: "Citizen",
    department: "stationery",
    category: "Калькуляторы",
    price: 890,
    stockQty: 22,
    tags: ["канцелярия"],
    description: "Большой дисплей, питание от сети и батареи. Для бухгалтерии.",
  }),
  p({
    id: "120310",
    sku: "CORR-TAPE",
    name: "Корректирующая лента Attache, 5 мм × 8 м",
    brand: "Attache",
    department: "stationery",
    category: "Корректоры",
    price: 79,
    tags: ["канцелярия"],
    description: "Сухое исправление. Можно сразу писать сверху.",
  }),

  p({
    id: "150101",
    sku: "NX-A15",
    name: "Ноутбук Acer Aspire 15, 15.6\", i5, 16 ГБ, 512 ГБ SSD",
    brand: "Acer",
    department: "computers",
    category: "Ноутбуки",
    price: 54990,
    stockQty: 4,
    attributes: { size: "15.6" },
    tags: ["техника"],
    description: "Рабочий ноутбук для офисных задач, Excel и видеосвязи.",
  }),
  p({
    id: "150102",
    sku: "M170",
    name: "Мышь беспроводная Logitech M170, USB-приёмник",
    brand: "Logitech",
    department: "computers",
    category: "Мыши",
    price: 890,
    stockQty: 55,
    tags: ["аксессуар"],
    description: "Компактная офисная мышь. Работает до 12 месяцев на одной батарейке.",
  }),
  p({
    id: "150103",
    sku: "BAG-156",
    name: "Сумка для ноутбука 15.6\", чёрная",
    brand: "Комус",
    department: "computers",
    category: "Сумки для ноутбуков",
    price: 1290,
    attributes: { size: "15.6" },
    tags: ["аксессуар"],
    description: "Плотная ткань, отделение для документов, плечевой ремень.",
  }),
  p({
    id: "150104",
    sku: "HDMI-18",
    name: "Кабель HDMI 1.8 м, v1.4",
    brand: "Комус",
    department: "computers",
    category: "Кабели HDMI",
    price: 390,
    attributes: { length: "1.8 м" },
    tags: ["аксессуар"],
    description: "Для монитора, проектора и переговорной. Позолоченные контакты.",
  }),
  p({
    id: "150105",
    sku: "USB-32",
    name: "Флеш-накопитель USB 32 ГБ, Комус",
    brand: "Комус",
    department: "computers",
    category: "USB-накопители",
    price: 490,
    attributes: { capacity: "32 ГБ" },
    tags: ["аксессуар"],
    description: "Корпус-колпачок, металлическая петля. Для обмена файлами без облака.",
  }),
  p({
    id: "150106",
    sku: "PAD-MOUSE",
    name: "Коврик для мыши 220×180 мм, чёрный",
    brand: "Комус",
    department: "computers",
    category: "Коврики для мыши",
    price: 149,
    tags: ["аксессуар"],
    description: "Тканевая поверхность, резиновое основание.",
  }),
  p({
    id: "150110",
    sku: "ACER-238",
    name: "Монитор Acer 23.8\", Full HD, IPS, HDMI/VGA",
    brand: "Acer",
    department: "computers",
    category: "Мониторы",
    price: 12990,
    stockQty: 12,
    attributes: { size: "23.8" },
    tags: ["техника"],
    description: "Офисный монитор без рамки с трёх сторон. Крепление VESA.",
  }),

  p({
    id: "160201",
    sku: "CH-696",
    name: "Кресло офисное Chairman 696, ткань, чёрное",
    brand: "Chairman",
    department: "furniture",
    category: "Кресла офисные",
    price: 8490,
    stockQty: 10,
    tags: ["мебель"],
    description: "Сетка на спинке, регулировка высоты, подлокотники.",
  }),
  p({
    id: "160202",
    sku: "MAT-CHAIR",
    name: "Коврик защитный под кресло, 120×90 см, прозрачный",
    brand: "Комус",
    department: "furniture",
    category: "Коврики под кресло",
    price: 2190,
    attributes: { size: "120x90" },
    tags: ["аксессуар"],
    description: "Поликарбонат. Защищает линолеум и паркет от колёсиков.",
  }),
  p({
    id: "160210",
    sku: "DESK-140",
    name: "Стол офисный 1400×700 мм, белый",
    brand: "Комус",
    department: "furniture",
    category: "Столы офисные",
    price: 7990,
    stockQty: 6,
    attributes: { size: "1400x700" },
    tags: ["мебель"],
    description: "ЛДСП 16 мм, металлические опоры. Сборка за 20 минут.",
  }),
  p({
    id: "160220",
    sku: "PED-3",
    name: "Тумба подкатная 3 ящика, белая",
    brand: "Комус",
    department: "furniture",
    category: "Тумбы",
    price: 4590,
    tags: ["мебель"],
    description: "Центральный замок, колёсики. В комплект к столу 1400 мм.",
  }),

  p({
    id: "170301",
    sku: "DISP-SOAP",
    name: "Диспенсер для жидкого мыла Tork, 1 л, белый",
    brand: "Tork",
    department: "cleaning",
    category: "Диспенсеры для мыла",
    price: 1890,
    tags: ["профуборка"],
    description: "Настенный. Система S1. Ключ от случайного вскрытия.",
  }),
  p({
    id: "170302",
    sku: "SOAP-TORK",
    name: "Мыло жидкое Tork, 1 л, картридж",
    brand: "Tork",
    department: "cleaning",
    category: "Жидкое мыло",
    price: 390,
    unit: "картридж",
    attributes: { volume: "1 л" },
    tags: ["расходник"],
    description: "Нейтральный pH, без красителя. Совместим с диспенсером Tork S1.",
  }),
  p({
    id: "170303",
    sku: "TOWEL-TORK",
    name: "Полотенца бумажные Tork Singlefold, 200 шт., 2 слоя",
    brand: "Tork",
    department: "cleaning",
    category: "Бумажные полотенца",
    price: 189,
    unit: "упак",
    pack: "200 шт.",
    tags: ["расходник"],
    description: "Сложение ZZ. Для диспенсеров H3.",
  }),
  p({
    id: "170304",
    sku: "DISP-TOWEL",
    name: "Диспенсер для полотенец Tork H3, белый",
    brand: "Tork",
    department: "cleaning",
    category: "Диспенсеры для полотенец",
    price: 2190,
    tags: ["профуборка"],
    description: "Листовая выдача — меньше расход, чем у рулона.",
  }),
  p({
    id: "170305",
    sku: "TP-TORK",
    name: "Туалетная бумага Tork Advanced, 2 слоя, 8 рулонов",
    brand: "Tork",
    department: "cleaning",
    category: "Туалетная бумага",
    price: 420,
    unit: "упак",
    pack: "8 рул.",
    tags: ["расходник"],
    description: "Белая, тиснение. Для офисных санузлов.",
  }),
  p({
    id: "170310",
    sku: "BAG-120",
    name: "Мешки для мусора 120 л, ПВД, 50 шт., синие",
    brand: "Комус",
    department: "cleaning",
    category: "Мешки для мусора",
    price: 310,
    unit: "рулон",
    pack: "50 шт.",
    tags: ["расходник"],
    description: "Прочные, с завязками. Для офисной кухни и холла.",
  }),
  p({
    id: "170311",
    sku: "BIN-12",
    name: "Ведро-контейнер для мусора 12 л, с педалью",
    brand: "Комус",
    department: "cleaning",
    category: "Вёдра",
    price: 790,
    attributes: { volume: "12 л" },
    tags: ["профуборка"],
    description: "Нержавеющий корпус. Под мешки 20–30 л.",
  }),

  p({
    id: "180401",
    sku: "BOX-600",
    name: "Короб четырёхклапанный 600×400×400 мм, Т-23",
    brand: "Комус",
    department: "packaging",
    category: "Коробки картонные",
    price: 89,
    stockQty: 400,
    attributes: { size: "600x400x400" },
    tags: ["тара"],
    description: "Гофрокартон трёхслойный. Для склада и отгрузки.",
  }),
  p({
    id: "180402",
    sku: "BOX-300",
    name: "Короб четырёхклапанный 300×200×150 мм, Т-23",
    brand: "Комус",
    department: "packaging",
    category: "Коробки картонные",
    price: 29,
    stockQty: 800,
    attributes: { size: "300x200x150" },
    tags: ["тара"],
    description: "Малый короб под интернет-заказы и комплектующие.",
  }),
  p({
    id: "180410",
    sku: "TAPE-48",
    name: "Скотч упаковочный 48 мм × 66 м, 45 мкм",
    brand: "Комус",
    department: "packaging",
    category: "Скотч упаковочный",
    price: 79,
    stockQty: 260,
    attributes: { width: "48 мм" },
    tags: ["расходник"],
    description: "Прозрачный. Заклейка клапанов короба в один проход.",
  }),
  p({
    id: "180411",
    sku: "TAPE-GUN",
    name: "Диспенсер-пистолет для упаковочного скотча 50 мм",
    brand: "Комус",
    department: "packaging",
    category: "Диспенсеры для скотча",
    price: 390,
    attributes: { width: "50 мм" },
    tags: ["аксессуар"],
    description: "Металлический. Ускоряет упаковку на складе в 3–4 раза.",
  }),
  p({
    id: "180412",
    sku: "STRETCH-500",
    name: "Стретч-плёнка 500 мм, 20 мкм, 1,8 кг",
    brand: "Комус",
    department: "packaging",
    category: "Стретч-плёнка",
    price: 490,
    unit: "рулон",
    attributes: { width: "500 мм" },
    tags: ["расходник"],
    description: "Паллетная обмотка. Первичная и вторичная упаковка.",
  }),
  p({
    id: "180413",
    sku: "KNIFE-SAFE",
    name: "Нож безопасный для плёнки и скотча, скрытое лезвие",
    brand: "Комус",
    department: "packaging",
    category: "Ножи упаковочные",
    price: 159,
    tags: ["аксессуар"],
    description: "Не повреждает товар внутри короба. Сменные лезвия.",
  }),
  p({
    id: "180414",
    sku: "LBL-5840",
    name: "Этикетки самоклеящиеся 58×40 мм, 500 шт.",
    brand: "Комус",
    department: "packaging",
    category: "Этикетки",
    price: 210,
    unit: "рулон",
    pack: "500 шт.",
    attributes: { size: "58x40" },
    tags: ["расходник"],
    description: "Для маркировки коробов и полок. Под этикет-пистолет и лазер.",
  }),
  p({
    id: "180415",
    sku: "GUN-MX5500",
    name: "Этикет-пистолет однострочный, 8 символов",
    brand: "Комус",
    department: "packaging",
    category: "Этикет-пистолеты",
    price: 1290,
    tags: ["оборудование"],
    description: "Цена, дата, партия — прямо на коробе или ценнике.",
  }),

  p({
    id: "190501",
    sku: "ROBE-WHT",
    name: "Халат рабочий мужской, бязь, белый, р. 52-54",
    brand: "Комус",
    department: "workwear",
    category: "Халаты",
    price: 890,
    attributes: { size: "52-54" },
    tags: ["спецодежда"],
    description: "Для склада, лаборатории, пищевого производства.",
  }),
  p({
    id: "190502",
    sku: "GLOVE-PVC",
    name: "Перчатки х/б с ПВХ-точкой, 10 пар",
    brand: "Комус",
    department: "workwear",
    category: "Перчатки",
    price: 249,
    unit: "упак",
    pack: "10 пар",
    tags: ["расходник", "сиз"],
    description: "Базовая защита рук на складе и в цехе.",
  }),
  p({
    id: "190503",
    sku: "LOCKER-2",
    name: "Шкаф металлический для одежды, 2 секции",
    brand: "Комус",
    department: "workwear",
    category: "Шкафы металлические",
    price: 12990,
    stockQty: 3,
    tags: ["мебель", "сиз"],
    description: "Замок, вентиляционные отверстия, перекладина. Для раздевалки.",
  }),
  p({
    id: "190510",
    sku: "HELM-WHT",
    name: "Каска защитная, белая",
    brand: "Комус",
    department: "workwear",
    category: "Каски",
    price: 390,
    inStock: false,
    stockQty: 0,
    tags: ["сиз"],
    description: "ГОСТ. Регулировка оголовья. Временно нет на складе Москвы.",
  }),

  p({
    id: "200601",
    sku: "PHILIPS-CM",
    name: "Кофемашина капельная Philips, 1,2 л, 1000 Вт",
    brand: "Philips",
    department: "food",
    category: "Кофемашины",
    price: 5990,
    stockQty: 8,
    attributes: { volume: "1.2 л" },
    tags: ["кухня"],
    description: "Для офисной кухни на 8–12 человек. Противокапельная система.",
  }),
  p({
    id: "200602",
    sku: "LAV-1KG",
    name: "Кофе в зернах Lavazza Qualità Rossa, 1 кг",
    brand: "Lavazza",
    department: "food",
    category: "Кофе",
    price: 1490,
    unit: "упак",
    pack: "1 кг",
    stockQty: 36,
    tags: ["расходник", "кухня"],
    description: "Смесь арабики и робусты. Подходит к капельным и рожковым машинам.",
  }),
  p({
    id: "200603",
    sku: "JARDIN-250",
    name: "Кофе молотый Jardin Espresso di Milano, 250 г",
    brand: "Jardin",
    department: "food",
    category: "Кофе",
    price: 390,
    unit: "упак",
    pack: "250 г",
    tags: ["расходник", "кухня"],
    description: "Готов к заварке в капельной машине без жерновой кофемолки.",
  }),
  p({
    id: "200604",
    sku: "CUP-200",
    name: "Стаканы бумажные однослойные 200 мл, 50 шт.",
    brand: "Комус",
    department: "food",
    category: "Стаканы бумажные",
    price: 189,
    unit: "упак",
    pack: "50 шт.",
    stockQty: 120,
    attributes: { volume: "200 мл" },
    tags: ["расходник", "кухня"],
    description: "Для кофе и чая на кухне. Подходят стандартные крышки 80 мм.",
  }),
  p({
    id: "200605",
    sku: "LID-80",
    name: "Крышки для стаканов 80 мм, 50 шт.",
    brand: "Комус",
    department: "food",
    category: "Крышки для стаканов",
    price: 129,
    unit: "упак",
    pack: "50 шт.",
    attributes: { size: "80 мм" },
    tags: ["расходник"],
    description: "С отверстием для питья. К стаканам 200–250 мл.",
  }),
  p({
    id: "200606",
    sku: "SUGAR-1KG",
    name: "Сахар-рафинад, 1 кг",
    brand: "Русский сахар",
    department: "food",
    category: "Сахар",
    price: 119,
    unit: "упак",
    pack: "1 кг",
    tags: ["расходник", "кухня"],
    description: "Кубики к чаю и кофе. Базовая закупка на кухню.",
  }),
  p({
    id: "200607",
    sku: "GF-100",
    name: "Чай Greenfield Earl Grey, 100 пакетиков",
    brand: "Greenfield",
    department: "food",
    category: "Чай",
    price: 420,
    unit: "упак",
    pack: "100 пак.",
    tags: ["расходник", "кухня"],
    description: "Чёрный чай с бергамотом. Для гостевых зон и переговорных.",
  }),
  p({
    id: "200608",
    sku: "NAPKIN-100",
    name: "Салфетки бумажные однослойные, 100 шт., белые",
    brand: "Комус",
    department: "food",
    category: "Салфетки",
    price: 59,
    unit: "упак",
    pack: "100 шт.",
    tags: ["расходник"],
    description: "На кухню и в переговорную к кофе.",
  }),
  p({
    id: "200610",
    sku: "KETTLE-1.7",
    name: "Чайник электрический Scarlett, 1,7 л, 2200 Вт",
    brand: "Scarlett",
    department: "food",
    category: "Чайники",
    price: 1490,
    stockQty: 15,
    attributes: { volume: "1.7 л" },
    tags: ["кухня"],
    description: "Автоотключение, фильтр от накипи. Для офисной кухни.",
  }),

  p({
    id: "210701",
    sku: "OP-4",
    name: "Огнетушитель порошковый ОП-4, закачной",
    brand: "Комус",
    department: "safety",
    category: "Огнетушители",
    price: 1290,
    stockQty: 28,
    attributes: { type: "ОП-4" },
    tags: ["пожарка"],
    description: "Класс А, В, С, Е. Обязателен в офисе по нормам пожарной безопасности.",
  }),
  p({
    id: "210702",
    sku: "STAND-OP",
    name: "Подставка напольная под огнетушитель, на 1 шт.",
    brand: "Комус",
    department: "safety",
    category: "Подставки для огнетушителей",
    price: 890,
    tags: ["аксессуар", "пожарка"],
    description: "Металл с полимерным покрытием. Не ставить огнетушитель на пол.",
  }),
  p({
    id: "210703",
    sku: "SIGN-EXT",
    name: "Знак «Огнетушитель», 200×200 мм, самоклеящийся",
    brand: "Комус",
    department: "safety",
    category: "Знаки пожарной безопасности",
    price: 89,
    tags: ["пожарка"],
    description: "ГОСТ 12.4.026. Указывает место размещения огнетушителя.",
  }),
  p({
    id: "210704",
    sku: "SIGN-EXIT",
    name: "Знак «Выход», 150×300 мм, фотолюминесцентный",
    brand: "Комус",
    department: "safety",
    category: "Знаки пожарной безопасности",
    price: 149,
    tags: ["пожарка"],
    description: "Светится в темноте. Для эвакуационных путей.",
  }),

  p({
    id: "220801",
    sku: "TERM-58",
    name: "Термоэтикетки 58×40 мм, 700 шт. в рулоне",
    brand: "Комус",
    department: "trade",
    category: "Термоэтикетки",
    price: 290,
    unit: "рулон",
    pack: "700 шт.",
    attributes: { size: "58x40" },
    tags: ["расходник", "торговля"],
    description: "Для весов и принтеров этикеток. Эко-термическая бумага.",
  }),
  p({
    id: "220802",
    sku: "CASH-57",
    name: "Лента для кассовых аппаратов 57 мм, 12 шт.",
    brand: "Комус",
    department: "trade",
    category: "Кассовая лента",
    price: 360,
    unit: "упак",
    pack: "12 шт.",
    attributes: { width: "57 мм" },
    tags: ["расходник", "торговля"],
    description: "Термолента 57×40×12. Для Атол, Эвотор, Вики Принт.",
  }),
  p({
    id: "220803",
    sku: "PRICE-RAIL",
    name: "Ценникодержатель на полку, 40 мм, 10 шт.",
    brand: "Комус",
    department: "trade",
    category: "Ценникодержатели",
    price: 240,
    unit: "упак",
    pack: "10 шт.",
    tags: ["торговля"],
    description: "Прозрачный пластик. Для торгового оборудования и склада самообслуживания.",
  }),
  p({
    id: "220810",
    sku: "PRINTER-ET",
    name: "Принтер этикеток Атол BP21, 203 dpi, USB",
    brand: "Атол",
    department: "trade",
    category: "Принтеры этикеток",
    price: 12990,
    stockQty: 5,
    attributes: { width: "58 мм" },
    tags: ["оборудование", "торговля"],
    description: "Термопечать. Для склада, курьерки и розницы.",
  }),
];

const byId = new Map(PRODUCTS.map((product) => [product.id, product]));

export function getProduct(id: string): Product | undefined {
  return byId.get(id);
}

export function listCategories(): string[] {
  return [...new Set(PRODUCTS.map((product) => product.category))].sort((a, b) =>
    a.localeCompare(b, "ru"),
  );
}

export function searchProducts(query: string): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return PRODUCTS;
  return PRODUCTS.filter((product) => {
    const hay = [
      product.name,
      product.brand,
      product.sku,
      product.id,
      product.category,
      product.description,
      ...product.tags,
    ]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}
