import type { ComplementRule } from "./types";

export const RULES: ComplementRule[] = [
  { id: "r1", fromCategory: "Принтеры лазерные", toCategory: "Картриджи лазерные", weight: 1, kind: "consumable", reason: "Картридж — обязательный расходник лазерного принтера" },
  { id: "r2", fromCategory: "Принтеры лазерные", toCategory: "Бумага офисная A4", weight: 0.86, kind: "consumable", reason: "Бумага A4 закрывает ежедневную печать" },
  { id: "r3", fromCategory: "МФУ струйные", toCategory: "Чернила", weight: 1, kind: "consumable", reason: "СНПЧ без чернил не печатает" },
  { id: "r4", fromCategory: "МФУ струйные", toCategory: "Бумага офисная A4", weight: 0.84, kind: "consumable", reason: "Офисная бумага для документов с МФУ" },
  { id: "r5", fromCategory: "МФУ струйные", toCategory: "Фотобумага", weight: 0.55, kind: "consumable", reason: "Цветное МФУ часто берут ещё и под фотопечать" },
  { id: "r6", fromCategory: "МФУ лазерные", toCategory: "Картриджи лазерные", weight: 1, kind: "consumable", reason: "Тонер к лазерному МФУ" },
  { id: "r7", fromCategory: "МФУ лазерные", toCategory: "Фотобарабаны", weight: 0.8, kind: "consumable", reason: "Барабан — отдельный расходник Brother" },
  { id: "r8", fromCategory: "МФУ лазерные", toCategory: "Бумага офисная A4", weight: 0.85, kind: "consumable", reason: "Бумага к лазерной печати" },
  { id: "r9", fromCategory: "Картриджи лазерные", toCategory: "Бумага офисная A4", weight: 0.62, kind: "workflow", reason: "Картридж без бумаги не закрывает задачу печати" },
  { id: "r10", fromCategory: "Чернила", toCategory: "Бумага офисная A4", weight: 0.58, kind: "workflow", reason: "Чернила + бумага — готовый комплект печати" },
  { id: "r11", fromCategory: "Ламинаторы", toCategory: "Плёнка для ламинирования", weight: 1, kind: "consumable", reason: "Плёнка — единственный расходник ламинатора" },
  { id: "r12", fromCategory: "Брошюраторы", toCategory: "Пружины для брошюрования", weight: 1, kind: "consumable", reason: "Пружины для переплёта" },
  { id: "r13", fromCategory: "Брошюраторы", toCategory: "Обложки для брошюрования", weight: 0.9, kind: "consumable", reason: "Обложки делают готовый регламент" },
  { id: "r14", fromCategory: "Уничтожители документов", toCategory: "Масло для шредеров", weight: 0.95, kind: "consumable", reason: "Масло продлевает ресурс ножей" },
  { id: "r15", fromCategory: "Степлеры", toCategory: "Скобы для степлера", weight: 1, kind: "consumable", reason: "Скобы нужного номера" },
  { id: "r16", fromCategory: "Дыроколы", toCategory: "Папки-регистраторы", weight: 0.7, kind: "workflow", reason: "Дырокол готовят документы в регистратор" },
  { id: "r17", fromCategory: "Папки-регистраторы", toCategory: "Файлы", weight: 0.88, kind: "consumable", reason: "Файлы защищают листы внутри папки" },
  { id: "r18", fromCategory: "Папки-регистраторы", toCategory: "Дыроколы", weight: 0.6, kind: "workflow", reason: "Без дырокола папку не заполнить" },
  { id: "r19", fromCategory: "Ручки шариковые", toCategory: "Стержни для ручек", weight: 0.8, kind: "consumable", reason: "Сменный стержень той же системы" },
  { id: "r20", fromCategory: "Доски магнитно-маркерные", toCategory: "Маркеры для досок", weight: 1, kind: "consumable", reason: "Маркеры — расходник доски" },
  { id: "r21", fromCategory: "Доски магнитно-маркерные", toCategory: "Губки для досок", weight: 0.9, kind: "accessory", reason: "Губка входит в рабочий комплект доски" },
  { id: "r22", fromCategory: "Доски магнитно-маркерные", toCategory: "Магниты", weight: 0.72, kind: "accessory", reason: "Магниты держат распечатки на доске" },
  { id: "r23", fromCategory: "Флипчарты", toCategory: "Бумага для флипчарта", weight: 1, kind: "consumable", reason: "Сменный блок бумаги" },
  { id: "r24", fromCategory: "Флипчарты", toCategory: "Маркеры для досок", weight: 0.82, kind: "consumable", reason: "Маркеры пишут по бумаге флипчарта" },
  { id: "r25", fromCategory: "Клеевые пистолеты", toCategory: "Клеевые стержни", weight: 1, kind: "consumable", reason: "Стержни нужного диаметра" },
  { id: "r26", fromCategory: "Скотч канцелярский", toCategory: "Диспенсеры для скотча", weight: 0.75, kind: "accessory", reason: "Диспенсер ускоряет отмотку ленты" },
  { id: "r27", fromCategory: "Ноутбуки", toCategory: "Мыши", weight: 0.78, kind: "accessory", reason: "Внешняя мышь для ежедневной работы" },
  { id: "r28", fromCategory: "Ноутбуки", toCategory: "Сумки для ноутбуков", weight: 0.82, kind: "accessory", reason: "Сумка в диагональ экрана" },
  { id: "r29", fromCategory: "Ноутбуки", toCategory: "Коврики для мыши", weight: 0.5, kind: "accessory", reason: "Коврик в рабочее место" },
  { id: "r30", fromCategory: "Мониторы", toCategory: "Кабели HDMI", weight: 0.88, kind: "accessory", reason: "HDMI — базовый кабель монитора" },
  { id: "r31", fromCategory: "Мыши", toCategory: "Коврики для мыши", weight: 0.7, kind: "accessory", reason: "Коврик стабилизирует датчик" },
  { id: "r32", fromCategory: "Кресла офисные", toCategory: "Коврики под кресло", weight: 0.8, kind: "accessory", reason: "Коврик бережёт пол и помогает колёсикам" },
  { id: "r33", fromCategory: "Столы офисные", toCategory: "Тумбы", weight: 0.65, kind: "accessory", reason: "Тумба закрывает хранение у стола" },
  { id: "r34", fromCategory: "Столы офисные", toCategory: "Кресла офисные", weight: 0.6, kind: "workflow", reason: "Стол без кресла — нерабочее место" },
  { id: "r35", fromCategory: "Диспенсеры для мыла", toCategory: "Жидкое мыло", weight: 1, kind: "consumable", reason: "Картридж мыла той же системы" },
  { id: "r36", fromCategory: "Диспенсеры для полотенец", toCategory: "Бумажные полотенца", weight: 1, kind: "consumable", reason: "Листовые полотенца под диспенсер" },
  { id: "r37", fromCategory: "Вёдра", toCategory: "Мешки для мусора", weight: 0.85, kind: "consumable", reason: "Мешки по объёму ведра" },
  { id: "r38", fromCategory: "Коробки картонные", toCategory: "Скотч упаковочный", weight: 0.95, kind: "consumable", reason: "Скотч закрывает клапан короба" },
  { id: "r39", fromCategory: "Коробки картонные", toCategory: "Стретч-плёнка", weight: 0.62, kind: "consumable", reason: "Плёнка фиксирует короб на паллете" },
  { id: "r40", fromCategory: "Коробки картонные", toCategory: "Диспенсеры для скотча", weight: 0.7, kind: "accessory", reason: "Пистолет ускоряет заклейку тиража" },
  { id: "r41", fromCategory: "Скотч упаковочный", toCategory: "Диспенсеры для скотча", weight: 0.88, kind: "accessory", reason: "Диспенсер под ширину 48–50 мм" },
  { id: "r42", fromCategory: "Скотч упаковочный", toCategory: "Ножи упаковочные", weight: 0.6, kind: "accessory", reason: "Безопасный нож для вскрытия" },
  { id: "r43", fromCategory: "Этикетки", toCategory: "Этикет-пистолеты", weight: 0.72, kind: "accessory", reason: "Пистолет печатает и клеит этикетку" },
  { id: "r44", fromCategory: "Халаты", toCategory: "Перчатки", weight: 0.55, kind: "workflow", reason: "СИЗ обычно закупают комплектом" },
  { id: "r45", fromCategory: "Халаты", toCategory: "Шкафы металлические", weight: 0.5, kind: "accessory", reason: "Шкаф для хранения спецодежды" },
  { id: "r46", fromCategory: "Кофемашины", toCategory: "Кофе", weight: 1, kind: "consumable", reason: "Кофе — расходник кофемашины" },
  { id: "r47", fromCategory: "Кофемашины", toCategory: "Стаканы бумажные", weight: 0.78, kind: "accessory", reason: "Одноразовые стаканы на офисную кухню" },
  { id: "r48", fromCategory: "Кофемашины", toCategory: "Сахар", weight: 0.64, kind: "accessory", reason: "Сахар к кофе в гостевой зоне" },
  { id: "r49", fromCategory: "Чайники", toCategory: "Чай", weight: 0.86, kind: "consumable", reason: "Чай — прямой расходник чайника" },
  { id: "r50", fromCategory: "Чайники", toCategory: "Стаканы бумажные", weight: 0.6, kind: "accessory", reason: "Посуда к чаю" },
  { id: "r51", fromCategory: "Стаканы бумажные", toCategory: "Крышки для стаканов", weight: 0.9, kind: "accessory", reason: "Крышка нужного диаметра" },
  { id: "r52", fromCategory: "Кофе", toCategory: "Стаканы бумажные", weight: 0.58, kind: "workflow", reason: "Кофе наливают в стакан" },
  { id: "r53", fromCategory: "Кофе", toCategory: "Сахар", weight: 0.5, kind: "workflow", reason: "Сахар часто берут вместе с кофе" },
  { id: "r54", fromCategory: "Огнетушители", toCategory: "Подставки для огнетушителей", weight: 0.95, kind: "accessory", reason: "Подставка — норма размещения" },
  { id: "r55", fromCategory: "Огнетушители", toCategory: "Знаки пожарной безопасности", weight: 0.8, kind: "accessory", reason: "Знак указывает место огнетушителя" },
  { id: "r56", fromCategory: "Принтеры этикеток", toCategory: "Термоэтикетки", weight: 1, kind: "consumable", reason: "Этикетки по ширине печати" },
  { id: "r57", fromCategory: "Принтеры этикеток", toCategory: "Кассовая лента", weight: 0.4, kind: "workflow", reason: "Рядом на кассовом узле" },
  { id: "r58", fromCategory: "Бумага офисная A4", toCategory: "Степлеры", weight: 0.45, kind: "workflow", reason: "Распечатки сшивают степлером" },
  { id: "r59", fromCategory: "Бумага офисная A4", toCategory: "Папки-регистраторы", weight: 0.42, kind: "workflow", reason: "Документы уходят в архив" },
];

export function findRule(fromCategory: string, toCategory: string): ComplementRule | undefined {
  return RULES.find(
    (rule) => rule.fromCategory === fromCategory && rule.toCategory === toCategory,
  );
}
